name: hoe
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.0
  args: ^2.1.0
  yaml: ^3.1.0
  process: ^4.2.1
  cli_util: ^0.3.0
  file: ^6.1.0
  shared_versions: ^2.0.0
  mustache_template: ^2.0.0
  http: ^0.13.4
  dio: ^4.0.6
  archive: ^3.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.10
