name: Run codegen

inputs:
  version:
    description: The version to run codegen
    default: 'rtc_4.3.0'
    type: string

runs:
  using: "composite"
  steps:
    - name: enable corepack
      run: corepack enable
    - name: set node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: Reconfigure git to use HTTP authentication
      run: |
        git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15.0.6" # Need ping version to 15.x
        directory: ${{ runner.temp }}/llvm
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Run code-gen
      run: |
        bash scripts/code_gen.sh ${{ inputs.version }}