name: Build agora_rtc_ng example

on: 
  workflow_dispatch:
    inputs:
      build_branch:
        description: agora_rtc_ng branch
        type: string
        required: true
        default: 'main'

      iris_windows_url:
        description: Iris windows url 
        required: true


jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check out build project
        uses: actions/checkout@v3
        with:
          repository: AgoraIO/Agora-Flutter-SDK
          ref: ${{ inputs.build_branch }}
          path: build_project

      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0'

      - name: Run build android
        run: |
          ls
          pwd
          ls build_project
          dart pub get
          dart run bin/hoe.dart build-agora-flutter-example --project-dir=build_project/Agora-Flutter-SDK --platforms=android --process-build --apple-package-name=io.agora.agoraRtcEngineExample --flutter-package-name=agora_rtc_engine
  # build_windows:
  #   name: Build agora_rtc_ng example Windows
  #   runs-on: windows-2019
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: '11'
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         flutter-version: '3.0.0'
  #     - run: flutter pub get
  #     - name: Run flutter build apk
  #       run: flutter build apk
  #       working-directory: example
