name: Build and post reuslt to the Pull Request

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: pull request target repo
        type: string
        required: true
        default: 'AgoraIO-Extensions/Agora-Flutter-SDK'

      target_branch:
        description: pull request target branch
        type: string
        required: true

      apple-package-name:
        description: The ios/macos bundle id, e.g., io.agora.agoraRtcEngineExample, io.agora.agorartm.agoraRtmExample
        type: string
        # Set default value `io.agora.agoraRtcEngineExample` to avoid introduce breaking changes to the `AgoraIO-Extensions/Agora-Flutter-SDK` repo.
        default: 'io.agora.agoraRtcEngineExample'

      flutter-package-name:
        description: The Flutter package name, e.g., agora_rtc_engine, agora_rtm
        type: string
        # Set default value `agora_rtc_engine` to avoid introduce breaking changes to the `AgoraIO-Extensions/Agora-Flutter-SDK` repo.
        default: 'agora_rtc_engine'

      pr_number:
        description: The pull request number
        type: number
        required: true

jobs:
  build_examples:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      repository: ${{ github.event.inputs.target_repo }}
      build_branch: ${{ github.event.inputs.target_branch }}
      apple-package-name: ${{ github.event.inputs.apple-package-name }}
      flutter-package-name: ${{ github.event.inputs.flutter-package-name }}

  comment_pr:
    name: Comment PR
    needs: build_examples
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Comment the artifactories download url to PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.ACTION_PAT }}
          issue-number: ${{ github.event.inputs.pr_number }}
          repository: ${{ github.event.inputs.target_repo }}
          body: |
            Examples built:
            - ${{ needs.build_examples.outputs.android_artifactory_download_url }}
            - ${{ needs.build_examples.outputs.ios_artifactory_download_url }}
            - ${{ needs.build_examples.outputs.macos_artifactory_download_url }}
            - ${{ needs.build_examples.outputs.windows_artifactory_download_url }}
            - ${{ needs.build_examples.outputs.web_artifactory_download_url }}

            > This comment is commented by bot, do not edit it directly

      - name: Remove label "ci:schedule_build_example"
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.ACTION_PAT }}
          repo: ${{ github.event.inputs.target_repo }}
          number: ${{ github.event.inputs.pr_number }}
          labels: |
            ci:schedule_build_example
            ci:building_example