name: Build agora_rtc_ng example

on: 
  workflow_dispatch:
    inputs:
      agora_rtc_ng_branch:
        description: agora_rtc_ng branch
        required: true
        default: 'main'

      iris_windows_url:
        description: Iris windows url 
        required: true


jobs:
  build_windows:
    name: Build agora_rtc_ng example Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0'
      - run: flutter pub get
      - name: Run flutter build apk
        run: flutter build apk
        working-directory: example
