name: Daily update doc

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  update_doc:
    name: Updating DOC
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Trigger update_doc workflow
        uses: actions/github-script@v6
        with:
          script: |
            const date = new Date()
            var dateString = `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`

            const owner = "littleGnAl"
            const repo = "hoe"
            const workflow_id = "update_doc.yml"
            const ref = 'main'

            // see https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
            // Only trigger Agora-Flutter-SDK repo at this time
            github.request(`POST /repos/${owner}/${repo}/actions/workflows/${workflow_id}/dispatches`, {
              ref: ref,
              inputs: {
                'iris-doc-ref': 'main',
                'target_repo': 'AgoraIO-Extensions/Agora-Flutter-SDK',
                'target_branch': 'main',
                'pull_request_title': `[doc] daily update ${dateString}`,
                'commit_message': `[doc] daily update ${dateString}`,
                'config': 'fmt_config/fmt_dart.yaml',
                'language': 'dart',
                'base-template-url': 'https://github.com/AgoraIO/agora_doc_source/releases/download/main/flutter_ng_json_template_en.json',
                'merge-template-url': '',
                'export-file-path': 'lib/agora_rtc_engine.dart'
              },
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })

     
