name: Update native sdk and iris dependencies

on: 
  workflow_dispatch:
    inputs:
      native_sdk_version:
        description: The content of the iris dependencies
        required: true
        type: string

      native_sdk_dependencies_content:
        description: The content of the native sdk dependencies
        type: string
        required: true

      iris_dependencies_content:
        description: The content of the iris dependencies
        required: true
        type: string

      base_tag_or_branch:
        description: The content of the iris dependencies
        required: true
        type: string

jobs:
  build_android:
    name: Build Android
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Check for release branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_PAT }}
          repository: AgoraIO/Agora-Flutter-SDK
          ref: ${{ inputs.base_tag_or_branch }}
          path: for-release-branch

      - name: Create and push new release branch
        run: |
          cd for-release-branch
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          BRANCH_NAME=special/${{ github.event.inputs.native_sdk_version }}
          git checkout -b ${BRANCH_NAME}
          git push -u origin ${BRANCH_NAME}

      - name: Check for update dependencies branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_PAT }}
          repository: AgoraIO/Agora-Flutter-SDK
          ref: "special/native-${{ inputs.native_sdk_version }}"
          path: for-update-dependencies-branch

      - name: Update native sdk and iris dependencies
        run: |
          PROJECT_DIR=$(pwd)/for-update-dependencies-branch
          NATIVE_SDK_DEPENDENCIES_CONTENT=${{ github.event.inputs.native_sdk_dependencies_content }}
          IRIS_DEPENDENCIES_CONTENT=${{ github.event.inputs.iris_dependencies_content }}

          
          dart pub get
          dart run bin/hoe.dart update-agora-flutter-native-dependencies \
            --project-dir=${PROJECT_DIR} \
            --native-sdk-dependencies-content=${NATIVE_SDK_DEPENDENCIES_CONTENT} \
            --iris-dependencies-content=${IRIS_DEPENDENCIES_CONTENT}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ACTION_PAT }}
          path: for-update-dependencies-branch
          commit-message: "feat: upgrade native sdk ${{ inputs.native_sdk_version }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: "littlegnal/special/native-${{ inputs.native_sdk_version }}"
          base: "special/native-${{ inputs.native_sdk_version }}"
          delete-branch: true
          draft: false
          title: "feat: upgrade native sdk ${{ inputs.native_sdk_version }}"
          body: |
            Update native sdk ${{ inputs.native_sdk_version }} dependencies

            > This pull request is trigger by bot, you can checkout this branch and update it.
          labels: |
            version:special