name: Update native sdk and iris dependencies

on: 
  workflow_dispatch:
    inputs:
      native_sdk_version:
        description: The native sdk version
        required: true
        type: string

      native_sdk_dependencies_content:
        description: The content of the native sdk dependencies
        type: string

      iris_dependencies_content:
        description: The content of the iris dependencies
        type: string

      base_tag_or_branch:
        description: The base branch or tag to release
        required: true
        type: string

jobs:
  setup_base_release_branch:
    name: Set up the base branch for releasing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for release branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_PAT }}
          repository: AgoraIO/Agora-Flutter-SDK
          ref: ${{ inputs.base_tag_or_branch }}
          path: AgoraIO/Agora-Flutter-SDK

      - name: Create and push new release branch
        run: |
          cd AgoraIO/Agora-Flutter-SDK
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          BRANCH_NAME=special/native-${{ inputs.native_sdk_version }}
          git checkout -b ${BRANCH_NAME}
          git push -u origin ${BRANCH_NAME}

  udpate_dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest
    needs: setup_base_release_branch
    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.17.1

      - uses: actions/checkout@v3

      - name: Check for update dependencies branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_PAT }}
          repository: AgoraIO/Agora-Flutter-SDK
          ref: "special/native-${{ inputs.native_sdk_version }}"
          path: AgoraIO/Agora-Flutter-SDK

      - name: Create and push new release branch
        run: |
          cd AgoraIO/Agora-Flutter-SDK
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          BRANCH_NAME=littlegnal/special/native-${{ inputs.native_sdk_version }}
          git checkout -b ${BRANCH_NAME}

      - name: Update native sdk and iris dependencies
        run: |
          PROJECT_DIR=$(pwd)/AgoraIO/Agora-Flutter-SDK
          NATIVE_SDK_DEPENDENCIES_CONTENT="${{ github.event.inputs.native_sdk_dependencies_content }}"
          IRIS_DEPENDENCIES_CONTENT="${{ github.event.inputs.iris_dependencies_content }}"
          
          dart pub get
          dart run bin/hoe.dart update-agora-flutter-native-dependencies \
            --project-dir=${PROJECT_DIR} \
            --native-sdk-dependencies-content="${NATIVE_SDK_DEPENDENCIES_CONTENT}" \
            --iris-dependencies-content="${IRIS_DEPENDENCIES_CONTENT}"

      - name: Create and push new release branch
        run: |
          cd AgoraIO/Agora-Flutter-SDK
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          BRANCH_NAME="littlegnal/special/native-${{ inputs.native_sdk_version }}"
          COMMIT_MSG="feat: upgrade native sdk ${{ inputs.native_sdk_version }}"
          git add .
          git commit -am "${COMMIT_MSG}"
          git push -u origin ${BRANCH_NAME}

          

      # - name: Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.ACTION_PAT }}
      #     path: AgoraIO/Agora-Flutter-SDK
      #     commit-message: "feat: upgrade native sdk ${{ inputs.native_sdk_version }}"
      #     committer: GitHub <noreply@github.com>
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     signoff: false
      #     branch: littlegnal/special/native-${{ inputs.native_sdk_version }}
      #     base: special/native-${{ inputs.native_sdk_version }}
      #     delete-branch: true
      #     draft: false
      #     title: "feat: upgrade native sdk ${{ inputs.native_sdk_version }}"
      #     body: |
      #       Update native sdk ${{ inputs.native_sdk_version }} dependencies

      #       > This pull request is trigger by bot, you can checkout this branch and update it.
      #     labels: |
      #       version:special

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTION_PAT }}
          script: |
            const branchName = `littlegnal/special/native-${{ inputs.native_sdk_version }}`;
            const baseBranchName = `special/native-${{ inputs.native_sdk_version }}`
            const body = `
            Update native sdk ${{ inputs.native_sdk_version }} dependencies

            > This pull request is trigger by bot, you can checkout this branch and update it.
            `;
            // https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#create-a-pull-request
            await github.request('POST /repos/{owner}/{repo}/pulls', {
              owner: 'AgoraIO-Extensions',
              repo: 'Agora-Flutter-SDK',
              title: `feat: upgrade native sdk ${{ inputs.native_sdk_version }}`,
              body: body,
              head: `${owner}:${branchName}`,
              base: baseBranchName,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });

  # schedule_build_examples:
  #   name: Schedule build examples
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   steps:
  #     - name: Schedule build examples
  #       uses: actions/github-script@v6
  #       with:
  #         github-token: ${{ secrets.ACTION_PAT }}
  #         script: |
  #           const branchName = `littlegnal/special/native-${{ inputs.native_sdk_version }}`;
  #           const baseBranchName = `special/native-${{ inputs.native_sdk_version }}`
  #           const body = `
  #           Update native sdk ${{ inputs.native_sdk_version }} dependencies

  #           > This pull request is trigger by bot, you can checkout this branch and update it.
  #           `;
  #           // https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#create-a-pull-request
  #           await github.request('POST /repos/{owner}/{repo}/pulls', {
  #             owner: 'AgoraIO-Extensions',
  #             repo: 'Agora-Flutter-SDK',
  #             title: `feat: upgrade native sdk ${{ inputs.native_sdk_version }}`,
  #             body: body,
  #             head: `${owner}:${branchName}`,
  #             base: baseBranchName,
  #             headers: {
  #               'X-GitHub-Api-Version': '2022-11-28'
  #             }
  #           });