name: Update doc

on: 
  workflow_dispatch:
    inputs:
      target_repo:
        description: pull request target branch
        type: string
        required: true
        default: 'AgoraIO/Agora-Flutter-SDK'

      target_branch:
        description: pull request target branch
        type: string
        required: true
        default: 'main'

      config:
        description: The language config
        type: string
        required: true
        default: 'fmt_config/fmt_dart.yaml'

      language:
        description: The language
        type: string
        required: true
        default: 'dart'

      template-url:
        description: The template url
        type: string
        required: true
        default: 'https://github.com/AgoraIO/agora_doc_source/releases/download/main/flutter_ng_json_template_cn.json'

      export-file-path:
        description: The export file path
        type: string
        required: true
        default: 'lib/agora_rtc_engine.dart'

jobs:
  update_doc:
    name: Updating DOC
    runs-on: macos-11
    timeout-minutes: 60
    steps:
      - name: Check out iris_doc
        uses: actions/checkout@v3
        with:
          repository: littleGnAl/iris-doc
          ref: main
          path: iris-doc

      - name: Check out build project
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.target_repo }}
          ref: ${{ inputs.target_branch }}
          path: ${{ inputs.target_repo }}

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0'

      - name: Run build macos
        run: |
          TARGET_REPO=${{ inputs.target_repo }}
          ROOT_PATH=$(pwd)
          cd iris-doc

          python3 -m pip install -r requirements.txt

          python3 iris_doc.py \
                  --config=${{ inputs.config }} \
                  --language=${{ inputs.language }} \
                  --template-url=${{ inputs.template-url }} \
                  --export-file-path=${ROOT_PATH}/${{ inputs.target_repo }}/${{ inputs.export-file-path }}
      # - name: Create commits
      #   run: |
      #     cd ${{ inputs.target_repo }}
      #     USER_NAME=${{ github.actor }}
      #     git config user.name "${USER_NAME}"
      #     git config user.email "${USER_NAME}@users.noreply.github.com"
      #     git commit -am "Update doc"
      #     git log
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ACTION_PAT }}
          path: ${{ inputs.target_repo }}
          commit-message: Update doc
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: "${{ inputs.target_branch }}-doc"
          base: ${{ inputs.target_branch }}
          delete-branch: true
          title: '[TEST] Update doc'
          body: |
            Update doc
          draft: false
